### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by anchal-gupta** [DeveloperAshish8/CodeChamp-s-Website#100]
Push notifications are small, pop-up messages sent to a user's device that appear even when the app isn't open. I am willing to integrate Push Notifications for Chrome & Firefox browser by which you can communicte to users about news, events and annoucements.

If you are interested in adding this feature to your project, I can go ahead and share some of the best notification providers that are available for free and on which I have already worked on.

**Comment by agarwalson02** [comment]
I am sure to process this task well within the assigned time by using javascript . So kindly assign this task to me @DeveloperAshish8

**Comment by DeveloperAshish8** [comment]
As a community, there is no need to send push notification to our members. Those who are willing to learn together are always welcomed
