### ISSUE TITLE
Improving the overall responsiveness on mobile

### ISSUE THREAD

**Issue by SanDiego2049** [DeveloperAshish8/CodeChamp-s-Website#102]
After using mobile simulator chrome extension on the demo link, I saw that the site needs major improvements on phone screens. Uncentered texts, leftover padding affecting cards and images, displaced buttons and so on. Kindly assign me to put the affairs in order.

**Comment by DeveloperAshish8** [comment]
Go ahead @SanDiego2049 .

**Comment by SanDiego2049** [comment]
The amount of work is overwhelming. You made use of both vanilla css in high amounts which isn't a good practice when using a framework already. What I'd suggest is scrapping the entire css file, removing non-bootstrap classes from the html file and building with bootstrap mainly then complimenting with a little css. in essence, my strong suggestion is restarting the entire project, that is the one thing that can help this project and future maintainers. Check out Net Ninja's tutorial on Bootstrap 5, it helped me in knowing most of the classes and their implementation and it can most definitely help you too.

**Comment by bhoopesh369** [comment]
Can i work on this issue

**Comment by sri-rishi** [comment]
Hey @DeveloperAshish8  can I work on this issue 

![image](https://user-images.githubusercontent.com/72429483/195993920-d13d79a5-1744-4d86-8039-534d24639707.png)
 
and also on hamburger is not visible in dark mode it's only visible on hover

**Comment by DeveloperAshish8** [comment]
Please create a new issue for the same @sri-rishi

**Comment by sri-rishi** [comment]
Sure
