### ISSUE TITLE
Improvement in Preloader 

### ISSUE THREAD

**Issue by DeveloperAshish8** [DeveloperAshish8/CodeChamp-s-Website#104]
The preloader is not displaying correctly.

The duration between home page and internship page is without preloader, you can add here also.

Anyone's who wants to work just comment down

**Comment by hamzailyas237** [comment]
I want to contribute to this issue for the hactoberfest purpose, please assign it to me.

**Comment by RishabhJain0721** [comment]
#Hi
 @DeveloperAshish8 do you want to add the preloder between the two pages ?
Please assign me.

**Comment by DeveloperAshish8** [comment]
Go ahead @hamzailyas237, don't forget to add video after edits in PR for quick review.

**Comment by hamzailyas237** [comment]
what do you want to show on loading?  The pre-loader.gif that was given. ?
