### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PravinPadalkar78** [DeveloperAshish8/CodeChamp-s-Website#113]
if we are in dark mode and tries to click on internship/jobs , website automatically changes to light mode . I would like to Fix this issue .
#hacktoberfest #bug

**Comment by PravinPadalkar78** [comment]
Please assign this issue to me ,so that i can start working on it

**Comment by DeveloperAshish8** [comment]
You are good to go @PravinPadalkar78 .
Please add a short video after fixing the issue in PR

**Comment by aakash-kumar-gorai** [comment]
hey @DeveloperAshish8, I worked on this issue to get it fixed please check my pr #125

**Comment by bhoopesh369** [comment]
Can I work on this issue @DeveloperAshish8

**Comment by prabhleenn** [comment]
Hey ! I would love to work on this by making my first Hacktoberfest submission.
It would be great if you assign me this.

**Comment by DeveloperAshish8** [comment]
Resolved in other PRs
