### ISSUE TITLE
Not redirecting team members profile to Linkedin when clicked on picture and name

### ISSUE THREAD

**Issue by Yasshu55** [DeveloperAshish8/CodeChamp-s-Website#122]
When we click on an image or name in the Our Team Members section, it does not redirect to the linkedin profile. it only redirects to the LinkedIn profile when click on LinkedIn image.

I would like to make it such a way that when clicked on the image and name it redirects to the linkedin profile.

I would like to work on this issue please assign it to me.

**Comment by DeveloperAshish8** [comment]
That's intensional @Yasshu55 , we have provided below a LinkedIn icon for better understanding as In mobile view user can slide left or right to see more team members.

**Comment by Yasshu55** [comment]
> That's intensional @Yasshu55 , we have provided below a LinkedIn icon for better understanding as In mobile view user can slide left or right to see more team members.

Ohk then it's fine...but my code does not affect how it looks in pc or mobile or any view. It looks the same, but when clicked on the name or image instead of the icon even then it redirects. As many times people on various screen sizes click on the image or name to open the profile.
