### ISSUE TITLE
Improvements to home page copy for the "Be a part of us" section 

### ISSUE THREAD

**Issue by MsMLyons** [DeveloperAshish8/CodeChamp-s-Website#124]
Hello, Dear Maintainers! 

I am participating in Hacktoberfest2022 and would like to make the following suggestions for the "Be a part of us" section of your home page by creating this issue. If you accept the issue, I am ready to create a pull request. 

Please consider my proposal for these small changes in the copy (text) of the section.

I am happy to also discuss any of the proposed changes with you. For example, perhaps you might prefer to only change the title on the cards, as outlined below, and to leave the paragraphs alone. 

PS - If you accept this issue, I would appreciate it if it were labeled with the Hacktoberfest2022 tag. 

Regardless of whether this issue is accepted, I thank you for the opportunity to present my ideas to you.

---------------------------------------------------------------------------------------------------------------------------------------------------

Proposal: Update the "Be a part of us" section by streamlining the section title and the language on cards to be more succinct.

Proposed changes:

1. Change the section title to "Join Our Communities"
2. Remove "page" from LinkedIn card
3. Change the paragraph on the LinkedIn card from "Follow our LinkedIn page where we post some tech stuff and get updated about our upcomng sessions.", to "Follow our LinkedIn profile for relevant tech posts and updates on our upcoming sessions."
4. Remove "server" from Discord card
5. Change the paragraph on the Discord card from "Join our Discord server to interact with the students around the globe also, ask your doubts with our mentors." to "Join our Discord server to interact with students around the globe and to ask our mentors your tech questions."
6. Remove "channel" from Telegram card
7. Change the paragraph on the Telegram card from "Join our telegram channel and get information about best resources and stay updated about opportunities." to "Join our telegram channel to get information about the best resources and stay up-to-date on opportunities."
8. Remove "page" from Instagram card
9. Change the paragraph on the Instagram card from "Follow us on Instagram to get programming memes, technical stuffs and short resources." to "Follow us on Instagram for resources and technical advice, as well as programming memes."
10. Correct the mistakes in the GitHub paragraph (no question mark; "fork" spelled "folk") and also make it more succinct by changing the text "Want to contribute to our website, folk the repository from here and start contributing." to "Want to contribute to our website? Fork the repository and start contributing!"
11. Remove "channel" from YouTube card
12. Change the paragraph on the YouTube card from "Subscribe our Channel on YouTube and get recorded sessions if you missed them." to "Subscribe to our YouTube channel for recorded sessions you may have missed."

To help visualize the above suggestions, compare the current version (first image) to the proposed updates (second image).

![image_2022-10-09_075918459](https://user-images.githubusercontent.com/81724942/194755630-1b558e96-0176-4a68-b591-db465a5e6c70.png)

![image_2022-10-09_111011519](https://user-images.githubusercontent.com/81724942/194764460-e5ebe4b9-b61d-4923-b02b-2a2dd121def8.png)

**Comment by DeveloperAshish8** [comment]
Go ahead @MsMLyons .
