### ISSUE TITLE
Enhance the UI of  " Be a Part of Us" section 

### ISSUE THREAD

**Issue by codingkush** [DeveloperAshish8/CodeChamp-s-Website#128]
I visited Codechamp website...and i found that the Be a Part of Us section is not looking good because cards are very simple..so i want to enhance the UI of this section by making Neumorphism cards so that it's look amazing 😍🤩

**Comment by DeveloperAshish8** [comment]
Please share the screenshot of what you want to  do ?

**Comment by codingkush** [comment]
Like this...

You can see that in this Be a Part Of Us section will looks amazing 🤩

![images (2)](https://user-images.githubusercontent.com/78756312/195623941-24bc3cc9-43df-4ff5-8984-a0a184b3a208.jpeg)
__

**Comment by codingkush** [comment]
Pls assign me this issue under hacktobetfest'22

**Comment by DeveloperAshish8** [comment]
Please share the screenshots of the word done for our website so, that it could be understandable by us that we need that or not @codingkush
