### ISSUE TITLE
Rewording of website copy

### ISSUE THREAD

**Issue by terrifricker** [DeveloperAshish8/CodeChamp-s-Website#134]
I found your repository in the Hacktoberfest discord channel looking for places to contribute.  Your site is incredible.  I'm still a beginning coder, but happen to be a native English speaker.  I might be more help in rewording some of the content of the copy on your site than helping with the coding.

I would like to suggest the following change to the description of CodeChamp.

From:

> CodeChamp is the Community of Coding Enthusiasts, where we provide Resources, share Roadmaps ,and give numerous Opportunities Updates in the field of Competitive Programming,Development and Cyber Security. Along with it,we organize various insightful Workshops, guidance Sessions for an apperentice to learn from new. In one line,"Together we aim to explore the untouched world of technology.

To:

> CodeChamp is a Community of Coding Enthusiasts providing Resources, sharing Roadmaps, and introducing numerous Opportunities. Get Updates in the field of Competitive Programming, Development, and Cyber Security. Join insightful Workshops and Guidance Sessions for new learners. In one line: "Together we aim to explore the untouched world of technology.”

**Comment by terrifricker** [comment]
I suggest the following changes to copy in the Be a Part of Us section.

![png-frameArtboard 1](https://user-images.githubusercontent.com/51532684/195168796-60a7a7b1-2e0d-46db-bb46-ce701b52e7f4.png)
![png-frameArtboard 2](https://user-images.githubusercontent.com/51532684/195168800-047acfa6-59ec-4e0f-bdd2-c193f2740bc6.png)
![png-frameArtboard 3](https://user-images.githubusercontent.com/51532684/195168802-c8a19b66-5027-436e-aac8-6ac359485419.png)
![png-frameArtboard 4](https://user-images.githubusercontent.com/51532684/195168805-a3eed945-7424-4791-9646-11df02adc817.png)
![png-frameArtboard 5](https://user-images.githubusercontent.com/51532684/195168807-01bb54b7-df62-476b-b40c-c1533b70c81c.png)

**Comment by terrifricker** [comment]
I would suggest the following changes for the Be a Part of Us section.
![png-frameArtboard 1](https://user-images.githubusercontent.com/51532684/195169236-0a849885-57f2-4310-9a19-4f09210a01c4.png)
![png-frameArtboard 2](https://user-images.githubusercontent.com/51532684/195169240-4acda36b-2b3b-4c7c-b2b0-5ef4f1d91b48.png)
![png-frameArtboard 3](https://user-images.githubusercontent.com/51532684/195169244-6c017a41-40f4-455f-ba9e-4d27acb36de6.png)
![png-frameArtboard 4](https://user-images.githubusercontent.com/51532684/195169245-f236fd4b-a5f3-4879-bb02-cd3528a3b88b.png)
![png-frameArtboard 5](https://user-images.githubusercontent.com/51532684/195169246-43dbea29-d4ba-40c2-939a-2e8f779c6934.png)

**Comment by DeveloperAshish8** [comment]
Good @terrifricker , but the required changes are already done in PR #135 .

**Comment by terrifricker** [comment]
How about just the changes to the description of CodeChamp on the home page?  The changes suggested are in my first comment.
