### ISSUE TITLE
Change GitHub Logo to White when shifting to dark-mode.

### ISSUE THREAD

**Issue by Vedant-Manjrekar** [DeveloperAshish8/CodeChamp-s-Website#143]
Change GitHub Logo (in join community) to White when shifting to dark-mode as it is not properly visible.

@DeveloperAshish8 I would like to work on it.

Please assign the issue to me.

**Comment by Vedant-Manjrekar** [comment]
Update:
@DeveloperAshish8 I have worked on the issue and its ready, if you assign me this issue i can quickly make a PR.

**Comment by DeveloperAshish8** [comment]
Please share some screenshots for better understanding.

**Comment by Vedant-Manjrekar** [comment]
Before: 
<img width="1429" alt="Screenshot 2022-10-15 at 8 51 55 PM" src="https://user-images.githubusercontent.com/93585735/195994519-684fec12-0072-41f7-ba98-04729c290f00.png">

After:
<img width="1440" alt="Screenshot 2022-10-15 at 8 53 43 PM" src="https://user-images.githubusercontent.com/93585735/195994534-49224964-8583-4f0f-912e-1a5f519c6257.png">

It will change according to light/dark mode

**Comment by Vedant-Manjrekar** [comment]
Hey @DeveloperAshish8 any update? I posted the screenshots.

**Comment by Vedant-Manjrekar** [comment]
@DeveloperAshish8 ??????

**Comment by DeveloperAshish8** [comment]
Ok create a PR for the same @Vedant-Manjrekar

**Comment by Vedant-Manjrekar** [comment]
> Ok create a PR for the same @Vedant-Manjrekar

@DeveloperAshish8 Done 👍🏽
