### ISSUE TITLE
changing hamburger color to white in dark mode

### ISSUE THREAD

**Issue by sri-rishi** [DeveloperAshish8/CodeChamp-s-Website#144]
![image](https://user-images.githubusercontent.com/72429483/195994642-1c349f5b-0cb0-48b1-8a67-d200e200aed4.png)

@DeveloperAshish8  can you please assign me this issue

**Comment by DeveloperAshish8** [comment]
Rename the issue to changing hamburger color to white in dard mode. @sri-rishi

**Comment by Jiya-garg9971** [comment]
please assign this issue to me under hacktoberfest.

**Comment by DeveloperAshish8** [comment]
Go ahead @sri-rishi
