### ISSUE TITLE
Improving the 'Why to join us?' section

### ISSUE THREAD

**Issue by Saloni098** [DeveloperAshish8/CodeChamp-s-Website#148]
There are errors in the description under the 'Why to join us?' section. I wish to correct them.

![description](https://user-images.githubusercontent.com/83643870/196025438-807af2cd-e6e9-4cc7-924f-c0be45ad4cf7.png)

Please assign it to me.

**Comment by DeveloperAshish8** [comment]
Please explain the errors @Saloni098 .

**Comment by dlucifer8** [comment]
@DeveloperAshish8 Let me point out some errors:
1. The bullet point text does not have the correct font size
2. Selection of a proper image so that it is suitable for both light and dark mode

 A bit of change to the files, and all will be good.
I hope you assign me the project.

**Comment by Saloni098** [comment]
> Please explain the errors @Saloni098 .

There are certain grammatical errors, for eg 'keeps to updated' , 'intership' etc.
Also, the image can be selected keeping in mind the light and dark modes.

**Comment by DeveloperAshish8** [comment]
Yes @Saloni098 , and please remove the background of the image for better UX.

Go for it.
