### ISSUE TITLE
Section title isn't getting displayed when clicked on navbar

### ISSUE THREAD

**Issue by taanii** [DeveloperAshish8/CodeChamp-s-Website#153]
When we click "About" or "Opportunities", or any other section on Navbar, it's showing the content but not the main heading of section. 

I would like to make the following changes for better user experience:

Before
![image](https://user-images.githubusercontent.com/54447400/196545002-5e5ed282-732a-4148-9d34-769c6b21949d.png)

After
![image](https://user-images.githubusercontent.com/54447400/196545078-57f22b2d-a355-44bc-8471-6b4aaa33cb56.png)

**Comment by DeveloperAshish8** [comment]
Go ahead @taanii .

**Comment by ishikajn8126** [comment]
Hey @DeveloperAshish8 can i take this up? The assignee seems to be inactive..

**Comment by DeveloperAshish8** [comment]
Go ahead @ishikajn8126 .
