### ISSUE TITLE
Add Margin After Every Section

### ISSUE THREAD

**Issue by Devashish-Bhandari** [DeveloperAshish8/CodeChamp-s-Website#155]
A little margin on top of every section would make the website look more beautiful and clean. 
Please allow me to add these margins.

This is how the website will look after that.

![margin-top](https://user-images.githubusercontent.com/96977199/196654533-b2c472b9-d445-4dc1-b609-5183a9561983.png)

![margin-top2](https://user-images.githubusercontent.com/96977199/196655086-81f4919c-8527-4a1d-8ac5-d14c8e84a499.png)

**Comment by DeveloperAshish8** [comment]
Its looking wider @Devashish-Bhandari . Please check out the already opened issues.
