### ISSUE TITLE
Making the Card's content center aligned

### ISSUE THREAD

**Issue by Devashish-Bhandari** [DeveloperAshish8/CodeChamp-s-Website#156]
The content of the card would look better when center aligned. 
Please allow me to make these changes.

Here's the screenshot of the same.

![cards-center](https://user-images.githubusercontent.com/96977199/196657215-b1907097-5694-483e-9237-f79736844f5d.png)

**Comment by DeveloperAshish8** [comment]
The current one is better than this one I think @Devashish-Bhandari . Do you have any other suggestion?

**Comment by Devashish-Bhandari** [comment]
I just noticed that the "Hacktoberfest" and the "Join Us" button follow the invalid way of linking a button to a Hyperlink according to the HTML 5 conventions.
The hyperlinks should be linked to button in this way.

`<form style="display: inline" action="http://example.com/" method="get">
  <button>Hacktoberfest</button>
</form>`

Can  I make those changes?
