### ISSUE TITLE
Enhancing the internships/jobs section

### ISSUE THREAD

**Issue by manika137** [DeveloperAshish8/CodeChamp-s-Website#160]
Hey @DeveloperAshish8, 
I'd like to add the title to the internships/jobs section which isn't present. Would also like to improve the visibility in the dark mode.
Please assign me this issue.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/80244229/196912546-f15530b8-1289-40b3-948c-dfdd9514b612.png">

**Comment by DeveloperAshish8** [comment]
Please share the screenshots post edits for better understanding.

**Comment by manika137** [comment]
Changes screenshots
<img width="960" alt="image" src="https://user-images.githubusercontent.com/80244229/197020789-019af0ab-ca7d-411d-a093-190f0fd19f38.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/80244229/197020880-18ea88ee-8edc-4ca8-860b-0e7b53e46177.png">

**Comment by DeveloperAshish8** [comment]
Go Ahead @manika137 .
