### ISSUE TITLE
Dark-mode bug

### ISSUE THREAD

**Issue by bhoopesh369** [DeveloperAshish8/CodeChamp-s-Website#163]
When toggling between internships/jobs page to others the dark-mode changes to white mode

**Comment by bhoopesh369** [comment]
can i work on this issue @DeveloperAshish8

**Comment by DeveloperAshish8** [comment]
Go ahead @bhoopesh369 .

**Comment by bhoopesh369** [comment]
I have submitted a PR @DeveloperAshish8

**Comment by bhoopesh369** [comment]
PR #164
