### ISSUE TITLE
Navbar does not change color to black in dark mode

### ISSUE THREAD

**Issue by lakshay007** [DeveloperAshish8/CodeChamp-s-Website#166]
this causes the navbar elements to be unreadable 
<img width="1512" alt="Screenshot 2022-10-23 at 11 41 55 AM" src="https://user-images.githubusercontent.com/34618792/197377001-862ca922-63bf-4858-b573-6078be4ff16c.png">
I would like to make it look something like this 
<img width="1512" alt="Screenshot 2022-10-23 at 11 37 43 AM" src="https://user-images.githubusercontent.com/34618792/197377014-55a2eacc-c559-4400-abd7-da849acc6276.png">
so you can assign it to me

**Comment by DeveloperAshish8** [comment]
Go ahead @lakshay007 .

**Comment by lakshay007** [comment]
@DeveloperAshish8 I fixed this and opened a pull request, please look into it
