### ISSUE TITLE
Multiple improvements to the Navbar

### ISSUE THREAD

**Issue by JP109** [DeveloperAshish8/CodeChamp-s-Website#169]
1. Navbar's text coincides with homepage's text. I would fix this by making the navbar opaque.
![image](https://user-images.githubusercontent.com/60847674/197377744-614eedad-14bb-4f1a-bc77-4d4646c9aadd.png)

2. Navbar's background stays white even while in dark mode. It's a bit hard on the eyes, so I'd like to assign it an appropriate dark shade.
![image](https://user-images.githubusercontent.com/60847674/197378006-0dfc6e0f-9d56-42e0-acca-c84d9ebff553.png)

3. Cursor doesn't change to type pointer when you hover on Navbar's toggle button. I'd like to fix this for better a UX.

**Comment by Rahulbaran** [comment]
I have also gone through the site and reason behind the second point (your 2nd point) is a bug. Try to refersh to the site and you will see it as dark

**Comment by JP109** [comment]
Looks like the bug has been fixed yeah. Closing the issue.
