### ISSUE TITLE
Opportunities section card's content and buttons are not alligned

### ISSUE THREAD

**Issue by Aman0786-git** [DeveloperAshish8/CodeChamp-s-Website#17]
Can you please assign me will fix it

**Comment by Arghya-Banerjee** [comment]
I would love to work on this issue, can you kidly assign me this issue?

**Comment by DeveloperAshish8** [comment]
Go for it @Arghya-Banerjee , please attach the screenshots after edits in the PR.

**Comment by DeveloperAshish8** [comment]
Go for it @Aman0786-git , please attach the Screenshots after edits in the PR.

**Comment by Aman0786-git** [comment]
> Go for it @Aman0786-git , please attach the Screenshots after edits in the PR or you can join our discord for better connection.

Sure ;-)

**Comment by Petsamuel** [comment]
Please assign this task to mee

**Comment by Aman0786-git** [comment]
@DeveloperAshish8 Can you please add hactoberfest label so that it can be counted and also I am not able to join your discord server I dont know is the link broken ?

**Comment by Aman0786-git** [comment]
[https://github.com/DeveloperAshish8/CodeChamp-s-Website/pull/57#issue-1393468654](url)
PR review @DeveloperAshish8

**Comment by Aman0786-git** [comment]
@DeveloperAshish8 PR Check

**Comment by ST1LLWATER** [comment]
Whats the status, can I pick up this?

**Comment by Aman0786-git** [comment]
> Whats the status, can I pick up this? Also please add hacktober label to this issue too!

I've made the changes waiting for the review
