### ISSUE TITLE
Scroll to top 🔝 button 

### ISSUE THREAD

**Issue by Muhammad235** [DeveloperAshish8/CodeChamp-s-Website#171]
I want to make the scroll to top button display when the page is scrolled and not fixed.

**Comment by DeveloperAshish8** [comment]
Please share a video or gif that you want to do @Muhammad235 .

**Comment by Muhammad235** [comment]
This is an example https://aspireclub100.netlify.app/ the scroll to top button pops up until you scroll and not fixed

**Comment by Muhammad235** [comment]
Could you please assign this task to me

**Comment by DeveloperAshish8** [comment]
Go ahead @Muhammad235
