### ISSUE TITLE
Email mentioned in the footer could be presented differently.

### ISSUE THREAD

**Issue by Ajith6901** [DeveloperAshish8/CodeChamp-s-Website#174]
Currently ,
the mail mentioned below "Patna ,India". is just written in plain 

![Screen Shot 2022-10-23 at 11 22 49 PM](https://user-images.githubusercontent.com/79219844/197407960-5292f749-7cb4-4745-8fea-c14f2f5c8b77.png)

But we could change it in such a way that when someone hits the mail id , automatically open their email client , add the your  email in the "To address"

![Screen Shot 2022-10-23 at 11 25 12 PM](https://user-images.githubusercontent.com/79219844/197408044-b8652398-e879-4378-aae9-f8e6d00c1eaf.png)

The below app(my email client ) was opened and added the  email in " to address " automatically. (once I clicked the email id )

![Screen Shot 2022-10-23 at 11 29 50 PM](https://user-images.githubusercontent.com/79219844/197408070-091d42a5-772a-4e35-a51c-dd0d6f4472de.png)

Please , allow me to add this functionality . Thank you

**Comment by Ajith6901** [comment]
Also , I could change the color to original text  as well. just adding the functionality only.

**Comment by DeveloperAshish8** [comment]
already corrected in other PRs
