### ISSUE TITLE
Enhanced Contacts section 

### ISSUE THREAD

**Issue by Akansha0211** [DeveloperAshish8/CodeChamp-s-Website#176]
Hey @DeveloperAshish8  if you have noticed carefully the form was looking quite weird in the Contacts section, as it was sticked with the image , also its width is too much.

How it was looking earlier
![image](https://user-images.githubusercontent.com/49263297/197419476-5ab8b1f7-df63-4b1c-a076-2a21a9dd4844.png)

The new look
![image](https://user-images.githubusercontent.com/49263297/197419493-c8ea5ba9-62eb-4bc1-935d-32aed0f7580d.png)

**Comment by Akansha0211** [comment]
@DeveloperAshish8  plz do let me know if more changes comes to your mind.

**Comment by DeveloperAshish8** [comment]
Go ahead @Akansha0211
