### ISSUE TITLE
Adding social media icons with hover effect in footer section

### ISSUE THREAD

**Issue by DeveloperAshish8** [DeveloperAshish8/CodeChamp-s-Website#18]
Please include an image in your pull request if assigned

**Comment by abitsalihu** [comment]
Hey @DeveloperAshish8, I would like to work on this issue. :)

**Comment by DeveloperAshish8** [comment]
Ok @abitsalihu , but we will be accepting PR from 1st October as this is a dedicated issue for hacktoberfest.

**Comment by abitsalihu** [comment]
@DeveloperAshish8 Okay that works for me, just assign me when u want if finished. :)

**Comment by RathoreAbhiii** [comment]
Can I work on this as well @DeveloperAshish8 ?

**Comment by BinniesLite** [comment]
Hi, I would like to work on this issue too

**Comment by devilkiller-ag** [comment]
Can I work on this?

**Comment by DeveloperAshish8** [comment]
I will be assigning for this issue on 30th September, till than explore the project more and join the contribution chat on our discord server.

**Comment by Shaliniyadav8130** [comment]
Hello sir, I want to work on this issue. Please assign me this issue

**Comment by Petsamuel** [comment]
Would like to work on this too

**Comment by Janhvi52** [comment]
Hello sir, @DeveloperAshish8 
I've handled these kind of issues earlier as well thus i can come up with a more fascinating solution to the same .Kindly assign me the issue so that i can start working on it,Thanyou!l

**Comment by SattyamSamania** [comment]
Hey @DeveloperAshish8. Can you assign this issue to me. I can make hover effect in the footer area. If assigned this issue plz tell further what should I do.

**Comment by lognoroy** [comment]
Sir, I have experience in this, please give me a chance.

**Comment by SonakshiChauhan** [comment]
Hello @DeveloperAshish8 I would like to contribute my learning to this project. Please if you could give me a chance.

**Comment by achiverram28** [comment]
Please assign this to me
