### ISSUE TITLE
Mistakes in home page ( grammatical)

### ISSUE THREAD

**Issue by anjaligoswami** [DeveloperAshish8/CodeChamp-s-Website#184]
Hey! @DeveloperAshish8 
There are some spelling and grammatical mistakes in the home page. It is not looking good. So, I want to fix it.
Here is a screenshot of it:
![image](https://user-images.githubusercontent.com/75528719/198090583-5eea57fc-1e6f-4fb1-a5fc-78d3277a2604.png)

Please assign this issue to me, so that I can fix it asap :)

**Comment by DeveVivek** [comment]
Can you please assign me this task.

**Comment by DeveloperAshish8** [comment]
Not accepting minor changes
