### ISSUE TITLE
improvement in internship/jobs cards

### ISSUE THREAD

**Issue by ishikajn8126** [DeveloperAshish8/CodeChamp-s-Website#189]
made some alignment changes in the the 1st card (can be compared with 2nd card -the current ui of all cards)
 i would like to make these changes to all cards if it seems valuable

![image](https://user-images.githubusercontent.com/72145053/198235844-134b5663-a24b-406f-93d4-4e704979c59a.png)

**Comment by DeveloperAshish8** [comment]
Not making major difference @ishikajn8126
