### ISSUE TITLE
Enhancing the UI of Intership section for better user experience ✌️.

### ISSUE THREAD

**Issue by DeveloperAshish8** [DeveloperAshish8/CodeChamp-s-Website#19]
Please include the image in the pull request if assigned.

**Comment by Anurag607** [comment]
I would like to work on this issue

**Comment by ShravaniAK** [comment]
please assign me this issue

**Comment by DeveloperAshish8** [comment]
Sure @ShravaniAK , I will be assigning this issue on 30th sep till than explore the project more and join the contributors chats on our discord from description.

**Comment by Janhvi52** [comment]
Hello sir, @DeveloperAshish8 
I've handled these kind of issues earlier as well thus i can come up with a more fascination solution to the same .Kindly assign me the issue so that i can start working on it,Thanyou!

**Comment by DeveloperAshish8** [comment]
Hey @ShravaniAK , please attach an image or video in the PR.
