### ISSUE TITLE
fix preloader z-index, up for grabs??

### ISSUE THREAD

**Issue by Timmotal** [DeveloperAshish8/CodeChamp-s-Website#193]
i added design and i'm currently working on another project, and i figured this out at the last last moment

![zindex_problem](https://user-images.githubusercontent.com/43627445/198329592-371358e8-5783-4f8c-ba0c-e76f3b1c7d78.jpg)

**Comment by DeveloperAshish8** [comment]
Attach a gif or video for better understanding @Timmotal .

**Comment by Timmotal** [comment]
@DeveloperAshish8 
Here it is.
![codechamp](https://user-images.githubusercontent.com/43627445/198370791-463b34bc-0c1d-4042-8188-12ba5ef82431.gif)

**Comment by DeveloperAshish8** [comment]
No @Timmotal , it will affect UX badly , current one is better.

**Comment by Timmotal** [comment]
Alrighty.
