### ISSUE TITLE
make landing text bright in dark-mode, up for grabs?

### ISSUE THREAD

**Issue by Timmotal** [DeveloperAshish8/CodeChamp-s-Website#194]
![notBrightEnough](https://user-images.githubusercontent.com/43627445/198333513-b5c5ae21-f032-4f42-9ac0-b36689060d2b.jpg)

**Comment by DeveloperAshish8** [comment]
please add an image of after edits text as well.

**Comment by ayushrathore111** [comment]
sir i want to work on this can you assign me this issue..

**Comment by DeveloperAshish8** [comment]
Add an screenshot of what you can do @ayushrathore111

**Comment by ayushrathore111** [comment]
@DeveloperAshish8 _
![Screenshot (36)](https://user-images.githubusercontent.com/94514710/198869373-ac70f454-5a67-4b45-91a0-d5c6967cdc62.png)

**Comment by ayushrathore111** [comment]
![Screenshot (36)](https://user-images.githubusercontent.com/94514710/198871411-59a9fd97-50b4-4425-b499-218e7d013dfe.png)
@DeveloperAshish8 i have changed this ...

**Comment by DeveloperAshish8** [comment]
Go ahead @ayushrathore111
