### ISSUE TITLE
Brand logo is not properly aligned on smaller screen sizes

### ISSUE THREAD

**Issue by simransia** [DeveloperAshish8/CodeChamp-s-Website#196]
The navbar brand logo is not properly aligned on a smaller screen size. It is having unnecessary extra margin from the left which is not looking good.

![Screenshot (8)](https://user-images.githubusercontent.com/88017902/198817060-4b8b6c7c-4647-4c76-aee1-42274d79eea3.png)

**Comment by simransia** [comment]
Hello @DeveloperAshish8, please look into this issue and kindly assign it to me with a hacktobest label. I will be happy to work on it.

**Comment by DeveloperAshish8** [comment]
Go ahead @simransia .
