### ISSUE TITLE
bug : Text overlapping 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [DeveloperAshish8/CodeChamp-s-Website#199]
![image](https://user-images.githubusercontent.com/78332454/198868145-2c8ddf39-c5f1-463f-85c0-7f70980dbcdf.png)
nav bar buttons texts are overlapping with boxes content

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by ayushrathore111** [comment]
Please assign to me this issue i want to work on it.....
