### ISSUE TITLE
[IMPROVEMENT] : Links are opening in same tab

### ISSUE THREAD

**Issue by PritamSarbajna** [DeveloperAshish8/CodeChamp-s-Website#2]
Hey in the website when clicking  _Be a part of us_ section's any links they are opening in the same tab. If it opens in another tab it'd be great. If you think it's a valid issue feel free to assign me.

https://user-images.githubusercontent.com/90236635/184498664-8a110e67-aeda-4021-9f48-55ba199f0fb3.mp4

**Comment by DeveloperAshish8** [comment]
Go for it Pritam
