### ISSUE TITLE
Adding entertaining preloader in the website 🧑‍💻

### ISSUE THREAD

**Issue by DeveloperAshish8** [DeveloperAshish8/CodeChamp-s-Website#20]
Please attach an image in the pull request if you are assigned for this issue.

**Comment by divyanshraj0408** [comment]
Hey! this seems interesting, i would like to work on this issue for Hacktoberfest.

**Comment by melencholicmice** [comment]
Hello , I would like to work on this issue for Hacktoberfest

**Comment by DeveloperAshish8** [comment]
Sure @divyanshraj0408 , I will be assigning you this issue on 30th Sep till than explore the project more and join us on discord for more contribution chats.

**Comment by Janhvi52** [comment]
Hello sir, @DeveloperAshish8 
I've handled these kind of issues earlier as well thus i can come up with a more fascination solution to the same .Kindly assign me the issue so that i can start working on it,Thanyou!

**Comment by DeveloperAshish8** [comment]
Everyone refer to issue #30 for this, Durgesh is designing the preloader, One who will code the exact Design , I will be merging his/her PR.

**Comment by DeveloperAshish8** [comment]
Hey everyone who are working for this issue, please refer to the ux_guidelines for preloader recently added.
