### ISSUE TITLE
Bug : Reloading the page causes `Hacktoberfest` button to start flashing

### ISSUE THREAD

**Issue by a-parris21** [DeveloperAshish8/CodeChamp-s-Website#202]
While on the [CodeChamp home page](https://codechamp.tech/), reloading the page with cause the `Hacktoberfest` button to begin flashing as if it is being repeatedly hovered over with the cursor.  
This bug occurs when the page is reloaded via any method.  
Clicking the `Reload` button on the browser's ribbon or pressing `F5` on Windows also trigger the bug.

Example:  

![codechamps tech__flashing-hacktober-btn](https://user-images.githubusercontent.com/69469270/198923597-ccfea1d4-8b94-4e4d-bd65-4089e3400baa.gif)

This can be reproduced in these browsers: 
- Firefox
- Chrome
- Opera
- Opera GX

**Comment by DeveloperAshish8** [comment]
That's intensional @a-parris21 , we are disabling the button by tonight.

**Comment by a-parris21** [comment]
Ah, alright then.
