### ISSUE TITLE
Remove Outdated links for Internships/Jobs Portal

### ISSUE THREAD

**Issue by GundaSudarrshan** [DeveloperAshish8/CodeChamp-s-Website#25]
I would like to contribute this part, @DeveloperAshish8 can you please assign this issue to me 
More Information:
Some links in Internships and Jobs portal are outdated and not relevant to mentioned positions 
should update it with relevant links or remove those cards whose links are not working anymore

**Comment by GundaSudarrshan** [comment]
and if this project is in hacktoberfest-22 can you update the labels as well

**Comment by DeveloperAshish8** [comment]
Sorry @GundaSudarrshan , Our team is adding new Internships and removing the old once regularly. So we can,t assign it to you as of now.
