### ISSUE TITLE
Submit button in Contact section has no labeled name

### ISSUE THREAD

**Issue by nujovich** [DeveloperAshish8/CodeChamp-s-Website#27]
The submit button has no value tag set, so the browser sets the default value to the pre-configured user's language. In my case is in Spanish

![image](https://user-images.githubusercontent.com/48018975/192537468-38579473-3a3a-4555-b1c2-daa3d25ff774.png)

**Comment by nujovich** [comment]
Can I get assigned to this issue after Sept 30th? Thanks

**Comment by DeveloperAshish8** [comment]
Sorry, this is a minor edit can't me counted for hactoberfest.
