### ISSUE TITLE
Navigation made easier

### ISSUE THREAD

**Issue by thisisharsh7** [DeveloperAshish8/CodeChamp-s-Website#28]
When a user enters the **Internships/Jobs page** and clicks the other nav items, such as Events, Team, Opportunities, they are not redirected directly to the specific section, but rather only to the **homepage.**  I'd like to contribute to this issue, can you please assign it to me as part of **Hacktoberfest**?

**Comment by thisisharsh7** [comment]
kindly review this issue.

**Comment by DeveloperAshish8** [comment]
Please attach the video fixing the issue.
