### ISSUE TITLE
Collapse menu when user clicks on any menu options

### ISSUE THREAD

**Issue by nujovich** [DeveloperAshish8/CodeChamp-s-Website#29]
Currently, for mobile devices, when users click on any option from the menu, the application goes to that section but the menu doesn't collapse. It would be better that the menu returns to its place for a better user experience 

![image](https://user-images.githubusercontent.com/48018975/192759443-e9c2896a-124b-4efe-accb-f61ba233aa64.png)

**Comment by nujovich** [comment]
Can I be assigned to this issue? Thanks

**Comment by DeveloperAshish8** [comment]
Go ahead @nujovich
