### ISSUE TITLE
Designing a pre-loader for waiting screens 

### ISSUE THREAD

**Issue by itsdurgeshray** [DeveloperAshish8/CodeChamp-s-Website#30]
Design a dynamic pre-loader for the screens until the main screen launches.

**Comment by FireNdIce3** [comment]
Can I work on this issue?

**Comment by itsdurgeshray** [comment]
> Can I work on this issue?

Currently, I am working on this issue, you can work on the development once the designs are ready.

**Comment by FireNdIce3** [comment]
Sure,I would like to develop it !
