### ISSUE TITLE
paragraph in README file needs some changes (punctuations and delivery)

### ISSUE THREAD

**Issue by chaaals** [DeveloperAshish8/CodeChamp-s-Website#33]
Hi @DeveloperAshish8 , sorry if the PR came in first (new to contributing to open source), but I noticed some lapses on the delivery and punctuation of the repo description in the README file. I did some changes in PR #31 . Let me know if you need more or okay with the changes :)).

**Comment by DeveloperAshish8** [comment]
As this is a minor edit, this won't be counted in hacktoberfest @chaaals

**Comment by DeveloperAshish8** [comment]
closed with PR #31
