### ISSUE TITLE
Enable Dark Mode

### ISSUE THREAD

**Issue by Aman-0604** [DeveloperAshish8/CodeChamp-s-Website#34]
@DeveloperAshish8 Hey, I would like to add `feature of Dark Mode` to your website.

### Why it is necessary ?
According to stats user's loves to visit website websites which has dark mode as it soothes their eyes.
Believe me your website looks awesome in Dark Mode.😉

### Under what label I would like to do this task ?
As this is a very good feature and it enhances beauty of the website, applying the knowledge of colour contrasts I will like to open a pull request for the same on `2nd October under Hacktoberfest label`. Please assign me for the same.

Thanks✨

**Comment by shivamvishwakarm** [comment]
ok, I want to add this feature to your website.

**Comment by Aman-0604** [comment]
> ok, I want to add this feature to your website.

@shivamvishwakarm As open source community we all want to contribute to some organisations and projects but it is completely wrong if you want to take away the task which anyone else has raised and is working on.

I have raised this feature and have asked the author to assign it to me. 

From next time try to see issues where no one has been assigned or where no one is interested to that issue.

**Comment by DeveloperAshish8** [comment]
Go for it @Aman-0604

**Comment by Aman-0604** [comment]
@DeveloperAshish8 I have opened a pull request for the same, please check.

**Comment by DeveloperAshish8** [comment]
Closed with PR # 58
