### ISSUE TITLE
improve contact us section

### ISSUE THREAD

**Issue by leesha19** [DeveloperAshish8/CodeChamp-s-Website#35]
hey there , i want to improve contact us section as it is not matching with the website theme 
and i want to contribute here for hacktoberfest22

**Comment by krishna-raz** [comment]
Can i work on this issue?

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it under hacktoberfest'22

**Comment by GazalBandil** [comment]
hey i have a better experience with color theory and I want to work on this issue please assign me this .
