### ISSUE TITLE
improve website main part

### ISSUE THREAD

**Issue by leesha19** [DeveloperAshish8/CodeChamp-s-Website#36]
<img width="1280" alt="Screenshot 2022-10-02 at 2 01 26 PM" src="https://user-images.githubusercontent.com/88451246/193445318-a4688123-dbb4-49af-bce5-369b6e6a74ca.png">
hey there , i want to make this section more attractive . Please assign me this issue for #hacktoberfest22

**Comment by DeveloperAshish8** [comment]
Hey @leesha19 , the screenshot  provided is not visible. Please edit and reshare.

**Comment by leesha19** [comment]
> Hey @leesha19 , the screenshot provided is not visible. Please edit and reshare.

the image sould be in the right side and the content and buttons at left

**Comment by DeveloperAshish8** [comment]
Got for it @leesha19 , let's make it response for this device as well.

**Comment by leesha19** [comment]
Ohk

**Comment by leesha19** [comment]
> > Got for it @leesha19 , let's make it response for this device as well.
> 
> is this looking good if you liked then i will submit the PR
> 
> <img alt="Screenshot 2022-10-06 at 5 47 41 PM" width="1280" src="https://user-images.githubusercontent.com/88451246/194310733-7422575f-9828-45a9-b986-41f0f9a49e0b.png">

@DeveloperAshish8

**Comment by DeveloperAshish8** [comment]
Go ahead and create a PR

**Comment by leesha19** [comment]
> Go ahead and create a PR

#137 here it is check it
