### ISSUE TITLE
Improvements in website team member representation

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [DeveloperAshish8/CodeChamp-s-Website#46]
As I have seen on the website, the LinkedIn profile link of every team member is attached below the photo ID. Just wanted to suggest that you can add the GitHub profile of each member as well besides that LinkedIn profile link with the GitHub logo. It will make the website well documented, look cool and also help build a community larger and help contributors like to navigate to GitHub and see good GitHub content. Thanks.

**Comment by ShubhamJagtap2000** [comment]
@DeveloperAshish8 please review it.

**Comment by DeveloperAshish8** [comment]
Actually some of our team members doesn't have GitHub profile so , we are keeping a hold on it right now.

**Comment by ShubhamJagtap2000** [comment]
Fine.
