### ISSUE TITLE
Fix bug in README.md

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [DeveloperAshish8/CodeChamp-s-Website#47]
In the later part of this repo's README.md I encountered a bug regarding the GitHub profile link of another contributor. The link attached is `https://github.com/DeveloperAshish8/CodeChamp-s-Website/issues/new`, which on redirection tells that it doesn't exist. But 
`https://github.com/DeveloperAshish8` is a valid GitHub profile. You can fix this link issue.

**Comment by Aman-0604** [comment]
I have already opened a pull request for this !

**Comment by mritul** [comment]
Can i work on this issue?

**Comment by nabeel001** [comment]
@DeveloperAshish8 can you please clearly explain your issue as I was not able to locate the link that you have specified anywhere in the README.md
