### ISSUE TITLE
Improve FAQ section

### ISSUE THREAD

**Issue by nileshlad09** [DeveloperAshish8/CodeChamp-s-Website#60]
![image](https://user-images.githubusercontent.com/89249015/193440276-4b666197-82ca-4f26-8738-cdce02b938e4.png)

please assign this issue to me under hacktoberfest2022

**Comment by Shaba1406** [comment]
I want to work on this issue please assign me @DeveloperAshish8

**Comment by DeveloperAshish8** [comment]
The current one is better as compared to in the image you showed @nileshlad09
