### ISSUE TITLE
[FEATURE] Open graph 

### ISSUE THREAD

**Issue by Nakamcode** [DeveloperAshish8/CodeChamp-s-Website#61]
### An open graph is a preview image that shows when a link is shared on social media

An open graph increases the click rate of a link when shared. 

_for more info about open graphs read the blog below_
https://ahrefs.com/blog/open-graph-meta-tags/

### This website is missing an open graph
![captures_chrome-capture-2022-9-2 (1)](https://user-images.githubusercontent.com/89482825/193441813-511e874c-5a5e-4436-886c-eec936fb84a1.png)

**Comment by DeveloperAshish8** [comment]
Go ahead @Nakamcode

**Comment by Nakamcode** [comment]
sure, thanks
