### ISSUE TITLE
Hover on light and dark theme

### ISSUE THREAD

**Issue by kushaljgec2025** [DeveloperAshish8/CodeChamp-s-Website#62]
I can improve the effect on light and dark theme doing hover effect .Please assign me the work.
![hover_on](https://user-images.githubusercontent.com/108950724/193442119-c5caec87-3b74-46d4-bd2e-b66e2fc78017.png)

**Comment by naXa777** [comment]
is it the same issue that's resolved in this PR https://github.com/DeveloperAshish8/CodeChamp-s-Website/pull/63 ?

**Comment by DeveloperAshish8** [comment]
Sorry this is now fixed
