### ISSUE TITLE
UI improvement for the Navbar Section

### ISSUE THREAD

**Issue by subhashis2204** [DeveloperAshish8/CodeChamp-s-Website#68]
# Objective
I would like to improve the alignment and the overall UI experience for the Navbar Section.

**Comment by DeveloperAshish8** [comment]
Please provide a clear look or attach some images in the issue description, which you want to add.

**Comment by subhashis2204** [comment]
![Screenshot (2141)](https://user-images.githubusercontent.com/76895635/193469036-6b23c21d-bce2-4b6e-a515-f064aaf1a9c6.png)

As we can see that the contents in the navbar are not aligned correctly. I can work on aligning them correctly. Moreover, we can see that the last element of the navbar touches the right boundary of the screen. Fixing the alignment would also fix this.

**Comment by mindexpert7546** [comment]
can you assign me

**Comment by sumitbaroniya** [comment]
please assign me this issue
