### ISSUE TITLE
Improvement in Scroll Bar 

### ISSUE THREAD

**Issue by Shaba1406** [DeveloperAshish8/CodeChamp-s-Website#72]
I Want to Improve the Scroll bar design. 
![CodeChamp - Google Chrome 02-10-2022 21_40_56](https://user-images.githubusercontent.com/97939567/193464508-15be6219-800d-4a5a-a2be-1de8eed3de90.png)
this is the current design of it want to enhance it more.

**Comment by ZahraShahid** [comment]
Can I contribute to this issue?

**Comment by DeveloperAshish8** [comment]
You are good to go @Shaba1406 ,
Please attach some images after edits in PR.
