### ISSUE TITLE
Add mailto: feature to the email button

### ISSUE THREAD

**Issue by Himanshuiiit** [DeveloperAshish8/CodeChamp-s-Website#87]
The email button directly redirect to the compose section of email but not to mailto:codechampcommunity@gmail.com.

This change will save some copy pasting and some rework.
Please allow me to wok in this.

**Comment by Anuragk9026** [comment]
@Himanshuiiit ,Please assign his issue to me

**Comment by ayushrathore111** [comment]
sir i wanna do this can you please assign it to me

**Comment by DeveloperAshish8** [comment]
Already corrected in some other PRs
