### ISSUE TITLE
Fix internship page on mobile view and improve internship cards

### ISSUE THREAD

**Issue by chaaals** [DeveloperAshish8/CodeChamp-s-Website#92]
## Description
Internship page needs a quick fix because a part of the footer section in the mobile UI is causing things to overflow. I also want to improve the internship cards by adding a transition to smoothen things out once a user hovers out of the card.

In addition to further improvements in the internship card, what do you think about clamping the about section to 5-6 lines?

## Screenshots
- Footer section in the mobile ui
![image](https://user-images.githubusercontent.com/70326902/193836263-29c8cc9e-2e51-4a95-9e82-b8d689d60861.png)
- Idea of clamping the about section, it should be similar to this but around 5 lines 
![image](https://user-images.githubusercontent.com/70326902/193836894-a2a23e03-2006-4adb-8464-0b0ef379a61b.png)

**Comment by DeveloperAshish8** [comment]
Go for it @chaaals .
