### ISSUE TITLE
Adding Carousel for the Feedback

### ISSUE THREAD

**Issue by Akansha0211** [DeveloperAshish8/CodeChamp-s-Website#96]
@DeveloperAshish8  Hey I have seen the website having carousel for the Feedback , so that people just can click on the right and left arrows to check more feedbacks , we can add some dummy also rn to check the Feature
![image](https://user-images.githubusercontent.com/49263297/193905205-13a90d0b-e8ed-4d59-b21c-8cbf956f2e08.png)

**Comment by DeveloperAshish8** [comment]
Yes @Akansha0211 , We can do that but right now we doesn't have enough feedbacks.

**Comment by Akansha0211** [comment]
okay no issues, will look for other things then
