### ISSUE TITLE
SUGGESTION: Improve the way we display internship cards

### ISSUE THREAD

**Issue by chaaals** [DeveloperAshish8/CodeChamp-s-Website#97]
## Description
Hey @DeveloperAshish8 ! Thanks for merging my latest PR ❤️. While I was working on it, I thought of an improvement that other people can contribute to. It's basically improving the way we display internship cards.

## Steps
In a script tag in the internships.html file
- Create an array of objects that contain all of the data for the internship card
Example:
![image](https://user-images.githubusercontent.com/70326902/193981988-19a1cc11-1087-4612-bdb8-7faafcea9202.png)

- Create a card template
Example: 
![image](https://user-images.githubusercontent.com/70326902/193982748-e79141e3-d79e-49bb-b307-6c50f75f94c1.png)

- Loop through the array of internship data and fill in the card template
- Target the internships-cards container and append each card template to it

## Additional context
It doesn't have to be me that implements this. Anyone can do it and it's just a suggestion so that in the future, it would be much easier to edit, add, and remove cards. However, if no one is willing to take this, I'd be more than happy to contribute this 😊.

**Comment by Akansha0211** [comment]
Hey @chaaals , you talking about JSX thing right. Need to inject React cdn inside that internships page itself and then that will work.

**Comment by theseus-alt** [comment]
I'd be happy to make this change!

**Comment by chaaals** [comment]
Hi @Akansha0211 ! You don't need React CDN for this one nor JSX. What you see above is a template string. You can append that inside a parent div and it will work.

**Comment by chaaals** [comment]
Sure @theseus-alt but wait for @DeveloperAshish8 to confirm this issue and label it as hacktoberfest

**Comment by Akansha0211** [comment]
okay @chaaals  got it.
